### ISSUE TITLE
Incorrect Values in Views with Descending Indices

### ISSUE THREAD

**Issue by superckl** [JuliaSIMD/StrideArraysCore.jl#18]
I've run across some strange behavior with stride arrays. When creating a view with indices that descend, it seems that nonsensical data is produced. Take the code snippet below.
```julia
init = zeros(10)
init .= 1:10
str = StrideArray(init)
println(view(str, 8:10))
println(view(str, 10:-1:8))
println(str[10:-1:8])
```
This outputs
```
[8.0, 9.0, 10.0]
[10.0, 9.704941046e-315, 1.47457394e-315]
[10.0, 9.0, 8.0]
```

It seems the first value in the view is correct, but the rest aren't. I have tried enabling bounds checking as suggested which made no difference. Normal array slicing appears to function correctly.

**Comment by chriselrod** [comment]
Thanks for the issue. Views with ranges whenever `step(r) != 1` were broken, but it should be fixed in 0.3.10.
