### ISSUE TITLE
Missing `elsize` method

### ISSUE THREAD

**Issue by ericphanson** [JuliaSIMD/StrideArraysCore.jl#44]
There is https://github.com/JuliaSIMD/StrideArraysCore.jl/blob/0b174fb3a1523d72e081a674ee836f83ffc59e35/src/ptr_array.jl#L488
but not a method that takes the type directly, as indicated in [the Julia manual](https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-strided-arrays):
```julia
@inline Base.elsize(::Type{<:StrideArraysCore.AbstractStrideArray{T}}) where {T} = sizeof(T)
```
without this, I got errors when passing a `StrideArray` though a flux model in https://github.com/ericphanson/AllocArrays.jl/blob/main/test/flux.jl.

**Comment by chriselrod** [comment]
Thanks for the issue, fixed.
