### ISSUE TITLE
move StrideArray type definition to this package?

### ISSUE THREAD

**Issue by Roger-luo** [JuliaSIMD/StrideArraysCore.jl#6]
just to file an issue that will prob resolve https://github.com/chriselrod/StrideArrays.jl/issues/21 so that I can just depend on this package.

**Comment by chriselrod** [comment]
From the [tests](https://github.com/JuliaSIMD/StrideArraysCore.jl/blob/6f65788f610bf41f8b4b7d7556d592fe6faf4e6e/test/runtests.jl#L131-L141):
```julia
greet = ["Hello", "world", "hang", "in", "there"]
greetsa = StrideArray(greet);
@test greetsa == greet
greetsa[1] = "howdy"
greetsa[5] = "there!"
@test greet[1] == "howdy"
@test greet[5] == "there!"
A = rand(ComplexF64, 4, 5);
Asa = StrideArray(A);
@test A == Asa
Asa[3,4] = 1234.5 + 678.9im;
@test A[3,4] == 1234.5 + 678.9im;
```
Also fixes the error you reported with `Complex` numbers.
Note adjoints of complex arrays are still broken.
